name: Create Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
      - name: Setup NodeJS 17
        uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Get Version Tag
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Create Zipped Artifact
        run: |
          zip -r module.zip . -x '*.git*'
      - name: Create Release
        uses: ncipollo/release-action@v1.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "module.json, module.zip"
          generateReleaseNotes: true
